config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'users/registrations', sessions: 'users/sessions' }

  root "pages#home"
  get 'shopping', to: 'shopping#index', as: 'shop'
  get 'public_recipes', to: 'public_recipes#index', as: 'public_recipes'
  get 'foods', to: 'food#index', as: 'foods'

  resources :recipes
  resources :food, only: %i[index new show create destroy] 
  
  resources :pages, only: %i[home] 
  get 'error', to: 'pages#error', as: 'error'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Recipe, public: true

    can :manage, Recipe, user_id: user.id unless user.nil?
    can :manage, Food, user_id: user.id unless user.nil?
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :inventory_foods, dependent: :destroy

  validates :name, presence: true, length: { maximum: 250 }
  validates :measuring_unit, presence: true, comparison: { greater_than_or_equal_to: 0 }
  validates :price, presence: true, comparison: { greater_than_or_equal_to: 0 }
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :user
  has_many :inventory_foods, dependent: :destroy
end

app/models/inventory_food.rb
class InventoryFood < ApplicationRecord
  belongs_to :inventory
  belongs_to :food
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy

  validates :name, presence: true, length: { maximum: 250 }
  validates :preparation_time, presence: true, length: { maximum: 10 }
  validates :cooking_time, presence: true, length: { maximum: 10 }
  validates :description, presence: true

  def total_price
    total = 0
    recipe_foods.each do |recipe_food|
      p recipe_food.food
      total += recipe_food.quantity * recipe_food.food.price
    end
    total / 1000
  end
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recipes, dependent: :destroy
  has_many :foods, dependent: :destroy
  has_many :inventories, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.json { head :forbidden }
      format.html { redirect_to error_path, alert: exception.message }
    end
  end
end

app/controllers/food_controller.rb
class FoodController < ApplicationController
  before_action :authenticate_user!, only: %i[index new create destroy]
  load_and_authorize_resource

  def index
    @foods = Food.where(user: current_user)
  end

  def show
    @food = Food.find(params[:id])
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)
    @food.user_id = current_user.id

    respond_to do |format|
      if @food.save
        format.html { redirect_to food_index_path(id: @food.user_id) }
        flash[:notice] = 'You have successfully created food.'
      else
        format.html { render :new, alert: 'An error has occurred while creating food' }
      end
    end
  end

  def destroy
    @food = Food.find(params[:id])

    @food.destroy if @food.present?
    respond_to do |format|
      format.html { redirect_to foods_path, notice: 'food was removed.' }
    end
  end

  def food_params
    params.require(:food).permit(:name, :measuring_unit, :price)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def error; end

  def home
    @foods = Recipe.includes(:recipe_foods).where(public: true).order(id: 'DESC')
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @recipes = Recipe.includes(:recipe_foods).where(public: true).order(id: 'DESC')
  end

  def show
    @recipe = Recipe.includes(:recipe_foods).find(params[:id])
    render 'public_recipes/404' if !@recipe.public && (!user_signed_in? || @recipe.user != current_user)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show edit update destroy]
  before_action :authenticate_user!, only: %i[new create destroy]
  load_and_authorize_resource

  def index
    @recipes = Recipe.where(user: current_user)
  end

  def show
    @recipe = Recipe.find(params[:id])
    render 'public_recipes/404' if !@recipe.public && (!user_signed_in? || @recipe.user != current_user)
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: 'recipe was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'recipe was successfully destroyed.' }
    end
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/controllers/shopping_controller.rb
class ShoppingController < ApplicationController
  before_action :authenticate_user!, only: %i[index]

  def index
    @shop = []
    @total = 0

    results = Food.joins(:recipe_foods).select(:foods, 'foods.*',
                                               'sum(recipe_foods.quantity) as rf_q').joins(:inventory_foods).select('inventory_foods.quantity as if_q').group('foods.id, inventory_foods.quantity')

    results.each do |result|
      next unless result.rf_q > result.if_q

      quantity = result.rf_q - result.if_q
      @shop << { food: result, quantity:, price: quantity * result.price }
      @total += quantity * result.price
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/food_helper.rb
module FoodHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/public_recipes_helper.rb
module PublicRecipesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/shopping_helper.rb
module ShoppingHelper
end

app/views/food/_food.html.erb
<div class="col-xl-4 col-lg-4 col-md-6">
  <div class="single_recepie text-center ml-3">
    <div class="recepie_thumb">
      <img src="img/recepie/recpie_2.png" alt="">
    </div>
    <h3><%= food.name %></h3>
    <h2>Measurement Unit:<%= food.measuring_unit %></h2>
    <h2>Unit Price: <%= food.price %></h2>
    <a href="#" class="line_btn"><%= button_to "Delete", food,class:"btn btn-warning btn-lg", method: :delete %></a>
  </div>
</div>

app/views/food/index.html.erb
<% content_for :page_title do %>
  Foods
<% end %>
<% content_for :header do %>
  <%= render partial: "/layouts/header" %>
<% end%>
<% content_for :content do %>
  <div class="recepie_area">
    <div class="p-5  d-flex align-items-center justify-content-center">
      <button type="button" class="btn btn-secondary btn-lg btn-block"><%= link_to "Add food", new_food_path %></button></div>
    <div class="container-fluid m-2">
      <div class="row">
        <% @foods.each do |f| %>
          <%= render partial: "food", locals: { food: f} %>
        <% end %>
      </div>
    </div>
  </div>
<%end%>

app/views/food/new.html.erb
<% content_for :page_title do %>
  Add food
<% end %>
<% content_for :header do %>
  <%= render partial: "/layouts/header" %>
<% end%>
<% content_for :content do %>
  <section class="container pt-5 mb-5">
    <div class="container">
      <h1>Add new food</h1>
      <%= form_with model: @food, url: food_index_path, class: "left" do |form| %>
        <%= form.label :Name %> <br>
        <%= form.text_field :name, class: 'form-control' %> <br>
        <%= form.label :Measuring_Unit %> <br>
        <%= form.text_field :measuring_unit, class: 'form-control' %> <br>
        <%= form.label :Price %> <br>
        <%= form.text_field :price, class: 'form-control' %> <br>
        <%= form.submit "Submit", class: "btn btn-info btn-lg" %>
      <% end %>
    </div>
  </section>
<%end%>

app/views/food/show.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col"><h2>Food</h2></th>
      <th scope="col"><h2>Measurement Unit</h2></th>
      <th scope="col"><h2>Unit Price</h2></th>
      <th scope="col"><h2>Action</h2></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <%# <th scope="row">1</th> %>
      <td> <h3><%= @food.name %></h3></td>
      <td><%= @food.measuring_unit %></h3></td>
      <td><h3><%= @food.price %></h3></td>
      <td><h3><%= link_to "Delete", food_path(id: @food.id ), data: {confirm: "Are you sure you want to delete: #{@food.name}?",}, method: :delete  %></h3></td>
    </tr>
  </tbody>
</table>

app/views/public_recipes/404.html.erb
<% content_for :header do %>
  <%= render partial: "/layouts/header" %>
<% end %>
<div>
  <% content_for :content do %>
    <div style="height: 400px;">
      Can not access this ressource
    </div>
  <% end %>
</div>

app/views/public_recipes/_recipe.html.erb
<div class="col-xl-4 col-lg-4 col-md-6">
  <div class="single_recepie text-center">
    <div class="recepie_thumb">
      <img src="/img/recepie/recpie_1.png" alt="recipe" />
    </div>
    <h3><%= recipe.name %></h3>
    <span>By: <%= recipe.user.name %></span>
    <span>Total food items:  <%= recipe.recipe_foods.length %></span>
    <span>Total price: <%= recipe.total_price %> </span>
    <%= link_to 'View Full Recipe', recipe_path(recipe), class: "line_btn" %>
  </div>
</div>

app/views/public_recipes/show.html.erb
<% content_for :page_title do %>
  <%= @recipe.name %>
<% end %>
<% content_for :header do %>
  <%= render partial: "/layouts/header" %>
<% end %>
<% content_for :content do %>
  <div class="recepie_details_area">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-xl-6 col-md-6">
          <div class="recepies_thumb">
            <img src="/img/recepie/recepie_details.png" alt="">
          </div>
        </div>
        <div class="col-xl-6 col-md-6">
          <div class="recepies_info">
            <h3><%= @recipe.name %></h3>
            <% if @recipe.public %>
              <div class="confirm-switch">
                <input type="checkbox" id="confirm-switch" checked=""  disabled>
                <label for="confirm-switch"></label>
              </div>
            <%end%>
            <p><%= @recipe.description%></p>
            <div class="resepies_details">
              <ul>
                <li>
                  <p><strong style="width: 130px;" >Rating</strong> : <i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i> </p>
                </li>
                <li>
                  <p><strong style="width: 130px;">Preparation time</strong> : <%= @recipe.preparation_time %> </p>
                </li>
                <li>
                  <p><strong style="width: 130px;">Cooking time</strong> : <%= @recipe.cooking_time %> </p>
                </li>
                <li>
                  <p><strong style="width: 130px;">Tags</strong> :  Dinner, Main, Chicken, Dragon, Phoenix </p>
                </li>
                <li>
                  <p>
                    <%= link_to shop_path do %>
                      <span class="genric-btn default circle arrow" style="width: 42%;margin: 10px;"> Generate shopping list</span>
                    <% end %>
                  </p>
                </li> 
                <% if can? :manage, @recipe %>
                  <li>
                    <p>
                      <span class="genric-btn default circle arrow" style="width: 42%;margin: 10px;"> Add ingredient</span></p>
                  </li>
                <% end %>
              </ul>
            </div>
            <div class="links">
              <a href="#"> <i class="fa fa-facebook"></i> </a>
              <a href="#"> <i class="fa fa-twitter"></i> </a>
              <a href="#"> <i class="fa fa-linkedin"></i> </a>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-xl-12">
          <div class="recepies_text">
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit.</p>
          </div>
        </div>
      </div>
      <br/>
      <div class="row">
        <div class="progress-table-wrap">
          <h3 class="text-heading">List of ingredient </h3>
          <div class="progress-table">
            <div class="table-head">
              <div class="serial"></div>
              <div class="percentage">Food</div>
              <div class="percentage">Quantity</div>
              <div class="percentage">Value</div>
              <div class="percentage"></div>
              <div class="percentage"></div>
            </div>
            <% @recipe.recipe_foods.each do |recipe_food| %>
              <div class="table-row">
                <div class="serial"></div>
                <div class="percentage"><%= recipe_food.food.name %></div>
                <div class="percentage"><%= recipe_food.quantity %></div>
                <div class="percentage">$ <%= recipe_food.food.price %></div>
                <div class="percentage"><a href="#" class="genric-btn success">Modify</a></div>
                <div class="percentage"><a href="#" class="genric-btn danger-border">Remove</a></div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-xl-12">
          <div class="recepies_text">
            <p></p>
            <p> Voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit. Voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<div class="recepie_area plus_padding">
  <div class="container-fluid ml-3">
    <div class="single_recepie text-center">
      <div class="d-flex justify-content-between container-fluid">
        <div class="d-flex flex-column">
          <h1><%= recipe.name %></h1>
          <div class="recepie_thumb mb-3">
            <img src="/img/recepie/recpie_1.png" alt="">
          </div>
          <h2 class="mb-3"><%= link_to "Show this recipe", recipe %></h2>
          <a href="#" class="line_btn"><%= button_to "Destroy this recipe", recipe_path(recipe), method: :delete, class:"btn btn-warning btn-lg" %></a>
        </div>
        <div class="d-flex p-5">
          <h3> <%= recipe.description %></h3>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/recipes/new.html.erb
<% content_for :page_title do %>
  Add recipe
<% end %>
<% content_for :header do %>
  <%= render partial: "/layouts/header" %>
<% end%>
<% content_for :content do %>
  <section class="contact-section section_padding">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <div>
            <%= link_to "Back to recipes", recipes_path %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-12">
        </div>
      </div>
      <div class="row">
        <div class="col-12">
          <h2 class="contact-title">Create a new recipe</h2>
        </div>
        <div class="col-lg-8 posts-list">
          <% if notice %>
            <p class="alert alert-success"><%= notice %></p>
          <% end %>
          <% if alert %>
            <p class="alert alert-danger"><%= alert %></p>
          <% end %>
          <%= render "form", recipe: @recipe %>
        </div>
        <div class="col-lg-4">
          <div class="blog_right_sidebar">
            <aside class="single_sidebar_widget search_widget">
              <form action="#">
                <div class="form-group">
                  <div class="input-group mb-3">
                    <input type="text" class="form-control" placeholder='Search Keyword'
                                 onfocus="this.placeholder = ''" onblur="this.placeholder = 'Search Keyword'">
                    <div class="input-group-append">
                      <button class="btn" type="button"><i class="ti-search"></i></button>
                    </div>
                  </div>
                </div>
                <button class="button rounded-0 primary-bg text-white w-100 btn_1 boxed-btn"
                           type="submit">Search</button>
              </form>
            </aside>
            <aside class="single_sidebar_widget instagram_feeds">
              <h4 class="widget_title">Instagram Feeds</h4>
              <ul class="instagram_row flex-wrap">
                <li>
                  <a href="#">
                    <img class="img-fluid" src="/img/post/post_5.png" alt="">
                  </a>
                </li>
                <li>
                  <a href="#">
                    <img class="img-fluid" src="/img/post/post_6.png" alt="">
                  </a>
                </li>
                <li>
                  <a href="#">
                    <img class="img-fluid" src="/img/post/post_7.png" alt="">
                  </a>
                </li>
                <li>
                  <a href="#">
                    <img class="img-fluid" src="/img/post/post_8.png" alt="">
                  </a>
                </li>
                <li>
                  <a href="#">
                    <img class="img-fluid" src="/img/post/post_9.png" alt="">
                  </a>
                </li>
                <li>
                  <a href="#">
                    <img class="img-fluid" src="/img/post/post_10.png" alt="">
                  </a>
                </li>
              </ul>
            </aside>
          </div>
        </div>
      </div>
    </div>
  </section>
<%end%>

app/views/recipes/show.html.erb
<% content_for :page_title do %>
  <%= @recipe.name %>
<% end %>
<% content_for :header do %>
  <%= render partial: "/layouts/header" %>
<% end %>
<% content_for :content do %>
  <div class="recepie_details_area">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-xl-6 col-md-6">
          <div class="recepies_thumb">
            <img src="/img/recepie/recepie_details.png" alt="">
          </div>
        </div>
        <div class="col-xl-6 col-md-6">
          <div class="recepies_info">
            <h3><%= @recipe.name %></h3>
            <% if @recipe.public %>
              <div class="confirm-switch">
                <input type="checkbox" id="confirm-switch" checked=""  disabled>
                <label for="confirm-switch"></label>
              </div>
            <%end%>
            <p><%= @recipe.description%></p>
            <div class="resepies_details">
              <ul>
                <li>
                  <p><strong style="width: 130px;" >Rating</strong> : <i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i> </p>
                </li>
                <li>
                  <p><strong style="width: 130px;">Preparation time</strong> : <%= @recipe.preparation_time %> </p>
                </li>
                <li>
                  <p><strong style="width: 130px;">Cooking time</strong> : <%= @recipe.cooking_time %> </p>
                </li>
                <li>
                  <p><strong style="width: 130px;">Tags</strong> :  Dinner, Main, Chicken, Dragon, Phoenix </p>
                </li>
                <li>
                  <p>
                    <%= link_to shop_path do %>
                      <span class="genric-btn default circle arrow" style="width: 42%;margin: 10px;"> Generate shopping list</span>
                    <% end %>
                  </p>
                </li>
                <% if can? :manage, @recipe %>
                  <li>
                    <p>
                      <span class="genric-btn default circle arrow" style="width: 42%;margin: 10px;"> Add ingredient</span></p>
                  </li>
                <% end %>
              </ul>
            </div>
            <div class="links">
              <a href="#"> <i class="fa fa-facebook"></i> </a>
              <a href="#"> <i class="fa fa-twitter"></i> </a>
              <a href="#"> <i class="fa fa-linkedin"></i> </a>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-xl-12">
          <div class="recepies_text">
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit.</p>
          </div>
        </div>
      </div>
      <br/>
      <div class="row ml-3">
        <div class="progress-table-wrap">
          <h3 class="text-heading">List of ingredient </h3>
          <div class="progress-table">
            <div class="table-head">
              <div class="serial"></div>
              <div class="percentage">Food</div>
              <div class="percentage">Quantity</div>
              <div class="percentage">Value</div>
              <div class="percentage"></div>
              <div class="percentage"></div>
            </div>
            <% @recipe.recipe_foods.each do |recipe_food| %>
              <div class="table-row">
                <div class="serial"></div>
                <div class="percentage"><%= recipe_food.food.name %></div>
                <div class="percentage"><%= recipe_food.quantity %></div>
                <div class="percentage">$ <%= recipe_food.food.price %></div>
                <div class="percentage"><a href="#" class="genric-btn success">Modify</a></div>
                <div class="percentage"><a href="#" class="genric-btn danger-border">Remove</a></div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-xl-12">
          <div class="recepies_text">
            <p></p>
            <p> Voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit. Voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>