config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'users/registrations', sessions: 'users/sessions' }

  root "pages#home"
  get 'shopping', to: 'shopping#index', as: 'shop'
  get 'public_recipes', to: 'public_recipes#index', as: 'public_recipes'
  get 'foods', to: 'food#index', as: 'foods'

  resources :recipes
  resources :food, only: %i[index new show create destroy] 
  
  resources :pages, only: %i[home] 
  get 'error', to: 'pages#error', as: 'error'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Recipe, public: true

    can :manage, Recipe, user_id: user.id unless user.nil?
    can :manage, Food, user_id: user.id unless user.nil?
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :inventory_foods, dependent: :destroy

  validates :name, presence: true, length: { maximum: 250 }
  validates :measuring_unit, presence: true, comparison: { greater_than_or_equal_to: 0 }
  validates :price, presence: true, comparison: { greater_than_or_equal_to: 0 }
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :user
  has_many :inventory_foods, dependent: :destroy
end

app/models/inventory_food.rb
class InventoryFood < ApplicationRecord
  belongs_to :inventory
  belongs_to :food
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy

  validates :name, presence: true, length: { maximum: 250 }
  validates :preparation_time, presence: true, length: { maximum: 10 }
  validates :cooking_time, presence: true, length: { maximum: 10 }
  validates :description, presence: true

  def total_price
    total = 0
    recipe_foods.each do |recipe_food|
      p recipe_food.food
      total += recipe_food.quantity * recipe_food.food.price
    end
    total / 1000
  end
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recipes, dependent: :destroy
  has_many :foods, dependent: :destroy
  has_many :inventories, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.json { head :forbidden }
      format.html { redirect_to error_path, alert: exception.message }
    end
  end
end

app/controllers/food_controller.rb
class FoodController < ApplicationController
  before_action :authenticate_user!, only: %i[index new create destroy]
  load_and_authorize_resource

  def index
    @foods = Food.where(user: current_user)
  end

  def show
    @food = Food.find(params[:id])
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)
    @food.user_id = current_user.id

    respond_to do |format|
      if @food.save
        format.html { redirect_to food_index_path(id: @food.user_id) }
        flash[:notice] = 'You have successfully created food.'
      else
        format.html { render :new, alert: 'An error has occurred while creating food' }
      end
    end
  end

  def destroy
    @food = Food.find(params[:id])

    @food.destroy if @food.present?
    respond_to do |format|
      format.html { redirect_to foods_path, notice: 'food was removed.' }
    end
  end

  def food_params
    params.require(:food).permit(:name, :measuring_unit, :price)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def error; end

  def home
    @foods = Recipe.includes(:recipe_foods).where(public: true).order(id: 'DESC')
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @recipes = Recipe.includes(:recipe_foods).where(public: true).order(id: 'DESC')
  end

  def show
    @recipe = Recipe.includes(:recipe_foods).find(params[:id])
    render 'public_recipes/404' if !@recipe.public && (!user_signed_in? || @recipe.user != current_user)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show edit update destroy]
  before_action :authenticate_user!, only: %i[new create destroy]
  load_and_authorize_resource

  def index
    @recipes = Recipe.where(user: current_user)
  end

  def show
    @recipe = Recipe.find(params[:id])
    render 'public_recipes/404' if !@recipe.public && (!user_signed_in? || @recipe.user != current_user)
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: 'recipe was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'recipe was successfully destroyed.' }
    end
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/controllers/shopping_controller.rb
class ShoppingController < ApplicationController
  before_action :authenticate_user!, only: %i[index]

  def index
    @shop = []
    @total = 0

    results = Food.joins(:recipe_foods).select(:foods, 'foods.*',
                                               'sum(recipe_foods.quantity) as rf_q').joins(:inventory_foods).select('inventory_foods.quantity as if_q').group('foods.id, inventory_foods.quantity')

    results.each do |result|
      next unless result.rf_q > result.if_q

      quantity = result.rf_q - result.if_q
      @shop << { food: result, quantity:, price: quantity * result.price }
      @total += quantity * result.price
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/food_helper.rb
module FoodHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/public_recipes_helper.rb
module PublicRecipesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/shopping_helper.rb
module ShoppingHelper
end

app/views/layouts/_header.html.erb
 <!-- header-start -->
<header>
  <div class="header-area">
    <div id="sticky-header" class="main-header-area">
      <div class="container-fluid ml-3">
        <div class="row align-items-center">
          <div class="col-xl-3 col-lg-2">
            <div class="logo">
              <a href="index.html">
                <img src="/img/logo.png" alt="" />
              </a>
            </div>
          </div>
          <div class="col-xl-6 col-lg-7">
            <div class="main-menu white_text d-none d-lg-block">
              <%= render partial: "/layouts/menu" %>
            </div>
          </div>
          <div class="col-xl-3 col-lg-3 d-none d-lg-block">
            <div class="search_icon">
              <a href="#">
                <i class="ti-search"></i>
              </a>
            </div>
          </div>
          <div class="col-12">
            <div class="mobile_menu d-block d-lg-none"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>
<!-- header-end -->
<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
  <div class="container-fluid">
    <div class="row">
      <div class="col-xl-12">
        <div class="bradcam_text text-center ml-5">
          <h3><%= yield :page_title %></h3>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- /bradcam_area  -->

app/views/layouts/_menu.html.erb
 <nav>
  <ul id="navigation">
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'Recipes', public_recipes_path %></li>
    <% if current_user %>
      <li><%= link_to 'My recipes', recipes_path %></li>
      <li><%= link_to 'Foods', foods_path %></li>
      <li><%= link_to 'Add recipe', new_recipe_path %></li>
      <li><%= button_to "logout", destroy_user_session_path, method: :delete  %></li>
    <% else %>
      <li><%= link_to "Sign up", new_user_registration_path %></li>
      <li><%= link_to "Sign in", new_user_session_path %></li>
    <% end %>
  </ul>
</nav>

app/views/layouts/_sections.html.erb
    <!-- latest_trand     -->
<div class="latest_trand_area">
  <div class="container">
    <div class="row">
      <div class="col-xl-12">
        <div class="trand_info text-center">
          <p>Thousands of recipes are waiting to be watched</p>
          <h3>Discover latest trending recipes</h3>
          <%= link_to 'View all Recipes', public_recipes_path, class: "boxed-btn3" %>
        </div>
      </div>
    </div>
  </div>
</div>
<!--/ latest_trand     -->
<!-- download_app_area -->
<div class="download_app_area plus_padding">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-xl-6 col-md-6">
        <div class="download_thumb">
          <div class="big_img">
            <img src="/img/video/big_1.png" alt="" />
          </div>
          <div class="small_01">
            <img src="/img/video/small_sm1.png" alt="" />
          </div>
          <div class="small_02">
            <img src="/img/video/sm2.png" alt="" />
          </div>
        </div>
      </div>
      <div class="col-xl-6 col-md-6">
        <div class="download_text">
          <h3>Download app to get recipes from Everywhere</h3>
          <div class="download_android_apple">
            <a class="active" href="#">
              <div class="download_link d-flex">
                <i class="fa fa-apple"></i>
                <div class="store">
                  <h5>Available</h5>
                  <p>on App Store</p>
                </div>
              </div>
            </a>
            <a href="#">
              <div class="download_link d-flex">
                <i class="fa fa-android"></i>
                <div class="store">
                  <h5>Download</h5>
                  <p>from Play Store</p>
                </div>
              </div>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!--/ download_app_area -->

app/views/layouts/application.html.erb
<!doctype html>
<html class="no-js" lang="zxx">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
     <meta
      name="image"
      property="og:image"
      sizes="512x512"
      content="%PUBLIC_URL%/favicon/android-chrome-512x512.png"
    />
    
    <title>Recipe App - Aniekan & Jihane</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- = stylesheet_link_tag "application", "data-turbo-track": "reload" % -->
    <!-- %= javascript_importmap_tags % -->
    <meta name="description" content="">
    <!-- <link rel="manifest" href="site.webmanifest"> -->
    <!-- Place favicon.ico in the root directory -->
    <!-- CSS here -->
    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/owl.carousel.min.css">
    <link rel="stylesheet" href="/css/magnific-popup.css">
    <link rel="stylesheet" href="/css/font-awesome.min.css">
    <link rel="stylesheet" href="/css/themify-icons.css">
    <link rel="stylesheet" href="/css/nice-select.css">
    <link rel="stylesheet" href="/css/flaticon.css">
    <link rel="stylesheet" href="/css/animate.min.css">
    <link rel="stylesheet" href="/css/slick.css">
    <link rel="stylesheet" href="/css/slicknav.css">
    <link rel="stylesheet" href="/css/style.css">
    <!-- <link rel="stylesheet" href="css/responsive.css"> -->
  <link rel="apple-touch-icon" sizes="180x180" href="%PUBLIC_URL%/favicon/apple-touch-icon.png">
  <link rel="icon" type="image/png" sizes="32x32" href="%PUBLIC_URL%/favicon/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="%PUBLIC_URL%/favicon/favicon-16x16.png">
  <link rel="manifest" href="%PUBLIC_URL%/favicon/site.webmanifest">
  </head>
  <body>
    <!--[if lte IE 9]>
      <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
    <![endif]-->
    <!-- header-start -->
    <%= yield :header %>
    <%= yield :content %>
    <%= yield :sections %>
    <!-- footer  -->
    <footer class="footer">
      <div class="footer_top">
        <div class="container-fluid ml-3">
          <div class="row">
            <div class="col-xl-2 col-md-6 col-lg-2">
              <div class="footer_widget">
                <h3 class="footer_title">
                  Top Products
                </h3>
                <ul>
                  <li><a href="#">Managed Website</a></li>
                  <li><a href="#"> Manage Reputation</a></li>
                  <li><a href="#">Power Tools</a></li>
                  <li><a href="#">Marketing Service</a></li>
                </ul>
              </div>
            </div>
            <div class="col-xl-2 col-md-6 col-lg-2">
              <div class="footer_widget">
                <h3 class="footer_title">
                  Quick Links
                </h3>
                <ul>
                  <li><a href="#">Jobs</a></li>
                  <li><a href="#">Brand Assets</a></li>
                  <li><a href="#">Investor Relations</a></li>
                  <li><a href="#">Terms of Service</a></li>
                </ul>
              </div>
            </div>
            <div class="col-xl-2 col-md-6 col-lg-2">
              <div class="footer_widget">
                <h3 class="footer_title">
                  Features
                </h3>
                <ul>
                  <li><a href="#">Jobs</a></li>
                  <li><a href="#">Brand Assets</a></li>
                  <li><a href="#">Investor Relations</a></li>
                  <li><a href="#">Terms of Service</a></li>
                </ul>
              </div>
            </div>
            <div class="col-xl-2 col-md-6 col-lg-2">
              <div class="footer_widget">
                <h3 class="footer_title">
                  Resources
                </h3>
                <ul>
                  <li><a href="#">Guides</a></li>
                  <li><a href="#">Research</a></li>
                  <li><a href="#">Experts</a></li>
                  <li><a href="#">Agencies</a></li>
                </ul>
              </div>
            </div>
            <div class="col-xl-4 col-md-6 col-lg-4">
              <div class="footer_widget">
                <h3 class="footer_title">
                  Subscribe
                </h3>
                <p class="newsletter_text">You can trust us. we only send promo offers,</p>
                <form action="#" class="newsletter_form">
                  <input type="text" placeholder="Enter your mail">
                  <button type="submit"> <i class="ti-arrow-right"></i> </button>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="copy-right_text">
        <div class="container">
          <div class="footer_border"></div>
          <div class="row align-items-center">
            <div class="col-xl-8 col-md-8">
              <p class="copy_right">
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                Copyright &copy;<script>
                  document.write(new Date().getFullYear());
                </script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
              </p>
            </div>
            <div class="col-xl-4 col-md-4">
              <div class="socail_links">
                <ul>
                  <li>
                    <a href="#">
                      <i class="ti-facebook"></i>
                    </a>
                  </li>
                  <li>
                    <a href="#">
                      <i class="ti-twitter-alt"></i>
                    </a>
                  </li>
                  <li>
                    <a href="#">
                      <i class="fa fa-dribbble"></i>
                    </a>
                  </li>
                  <li>
                    <a href="#">
                      <i class="fa fa-behance"></i>
                    </a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </footer>
    <!--/ footer  -->
    <!-- JS here -->
    <script src="/js/vendor/modernizr-3.5.0.min.js"></script>
    <script src="/js/vendor/jquery-1.12.4.min.js"></script>
    <script src="/js/popper.min.js"></script>
    <script src="/js/bootstrap.min.js"></script>
    <script src="/js/owl.carousel.min.js"></script>
    <script src="/js/isotope.pkgd.min.js"></script>
    <script src="/js/ajax-form.js"></script>
    <script src="/js/waypoints.min.js"></script>
    <script src="/js/jquery.counterup.min.js"></script>
    <script src="/js/imagesloaded.pkgd.min.js"></script>
    <script src="/js/scrollIt.js"></script>
    <script src="/js/jquery.scrollUp.min.js"></script>
    <script src="/js/wow.min.js"></script>
    <script src="/js/nice-select.min.js"></script>
    <script src="/js/jquery.slicknav.min.js"></script>
    <script src="/js/jquery.magnific-popup.min.js"></script>
    <script src="/js/plugins.js"></script>
    <script src="/js/gijgo.min.js"></script>
    <!--contact js-->
    <script src="/js/contact.js"></script>
    <script src="/js/jquery.ajaxchimp.min.js"></script>
    <script src="/js/jquery.form.js"></script>
    <script src="/js/jquery.validate.min.js"></script>
    <script src="/js/mail-script.js"></script>
    <script src="/js/main.js"></script>
  </body>
</html>

app/views/pages/error.html.erb
  <% content_for :content do %>
  <div style="height: 400px;">
    Can not access this ressource
  </div>
<% end %>

app/views/pages/home.html.erb
<% content_for :content do %>
  <header>
    <div class="header-area ">
      <div id="sticky-header" class="main-header-area ">
        <div class="container-fluid ml-3">
          <div class="row align-items-center">
            <div class="col-xl-3 col-lg-2">
              <div class="logo">
                <a href="index.html">
                  <img src="img/logo.png" alt="">
                </a>
              </div>
            </div>
            <div class="col-xl-6 col-lg-7">
              <div class="main-menu   d-none d-lg-block">
                <nav>
                  <%= render partial: "/layouts/menu" %>
                </nav>
              </div>
            </div>
            <div class="col-xl-3 col-lg-3 d-none d-lg-block">
              <div class="search_icon">
                <a href="#">
                  <i class="ti-search"></i>
                </a>
              </div>
            </div>
            <div class="col-12">
              <div class="mobile_menu d-block d-lg-none"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>
  <!-- slider_area_start -->
  <div class="slider_area ">
    <div class="single_slider  d-flex align-items-center slider_bg_1 ">
      <div class="container-fluid">
        <div class="row align-items-center justify-content-center">
          <div class="col-xl-8 ">
            <div class="slider_text text-center">
              <div class="text">
                <h3>
                  Chicken dish with per boiled egg 
                </h3>
              </div>
            </div>
          </div>
        </div>
        <div class="col-xl-3 col-lg-3 d-none d-lg-block">
          <div class="search_icon">
            <a href="#">
              <i class="ti-search"></i>
            </a>
          </div>
        </div>
        <%# <div class="col-12">
          <div class="mobile_menu d-block d-lg-none">
          </div> %>
        <%# </div> %>       
      </div>
    </div>
  </div>
</div>
<div class="recepie_area">
  <div class="container-fluid">
    <div class="row">
      <% @foods.each do |f| %>
        <div class="col-xl-4 col-lg-4 col-md-6">
          <div class="single_recepie text-center">
            <div class="recepie_thumb">
              <img src="/img/recepie/recpie_3.png" alt="">
            </div>
            <h3><%= f.name %></h3>
            <span>Appetizer</span>
            <p>Time Needs: 30 Mins</p>
            <%= link_to 'View Full Recipe', recipe_path(f), class: "line_btn" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<div class="recepie_videoes_area">
  <div class="container-fluid ml-3">
    <div class="row">
      <div class="col-xl-6 col-lg-6 col-md-6">
        <div class="recepie_info">
          <h3>Recipe videos 
            that never misses 
            any portion</h3>
          <p>inappropriate behavior is often laughed off as “boys will be boys,” women face higher conduct standards especially in the workplace. That’s why it’s crucial that, as women.</p>
          <div class="video_watch d-flex align-items-center">
            <a class="popup-video" href="https://www.youtube.com/watch?v=lr6AMBsjxrY"> <i class="ti-control-play"></i> </a>
            <div class="watch_text" >
              <h4>Watch Video</h4>
              <p>You will love our execution</p>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-6 col-md-6">
        <div class="videos_thumb">
          <div class="big_img">
            <img src="img/video/big.png" alt="">
          </div>
          <div class="small_thumb">
            <img src="img/video/small_1.png" alt="">
          </div>
          <div class="small_thumb_2">
            <img src="img/video/2.png" alt="">
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="latest_trand_area mb-5">
  <div class="container-fluid">
    <div class="row">
      <div class="col-xl-12">
        <div class="trand_info text-center">
          <p>Thousands of recipes are waiting to be watched</p>
          <h3>Discover latest trending recipes</h3>
          <a href="#" class="boxed-btn3">View all Recipes</a>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- slider_area_end -->
<!-- footer  -->
<%end%>